# SPDX-FileCopyrightText: 2013 The glucometerutils Authors
#
# SPDX-License-Identifier: MIT

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=Travis CI - Pull Request"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
  - name: Automatic merge from Flameeyes
    conditions:
      - "author=Flameeyes"
      - "status-success=Travis CI - Pull Request"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
